### ISSUE TITLE
新TweetDeck向けカスタム実装

### ISSUE THREAD

**Issue by Marco3jp** [Marco3jp/customDeck#13]
ほしいやつ

- スクロールバーの非表示
- 中幅、もうちょっとだけ細くなって欲しい
  - ツイートする枠を360px -> 300px(両サイドのpaddingも小さく)
  - 各カラムをいい感じに（今は380pxらしい、昔のTDで何pxにしてたかデータが残ってなかった、250pxは流石に細すぎ感あるし300pxで揃えてた可能性もある）
- ツイートする枠、丸い背景にしたら昔のTDぽくなるかな……

**Comment by Marco3jp** [comment]
```css
.css-1dbjc4n.r-1p0dtai.r-1d2f490.r-11yh6sk.r-1rnoaur.r-u8s1d.r-zchlnj.r-1bzj12m.r-ipm5af::-webkit-scrollbar {
    width: 4px;
}

.css-1dbjc4n.r-1p0dtai.r-1d2f490.r-11yh6sk.r-1rnoaur.r-u8s1d.r-zchlnj.r-1bzj12m.r-ipm5af::-webkit-scrollbar-thumb {
    background-color: rgba(158, 158, 158, 1);
}
```
